apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/version: {{ .Chart.Version }}
  annotations:
    ad.datadoghq.com/tags: '{"layer": "web"}'
spec:
  replicas: 2
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/version: {{ .Chart.Version }}
      annotations:
        ad.datadoghq.com/tags: '{"layer":"web"}'
        ad.datadoghq.com/{{ .Chart.Name }}.logs: '[{"source":"nginx"}]'
    spec:
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Chart.Name }}
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: ptcsmacr.azurecr.io/com.bosch.pt/csm.web.app:{{ .Chart.Version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: server
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
